### ISSUE TITLE
Error in prov.init(...)

### ISSUE THREAD

**Issue by ngohoanglankhanh** [End-to-end-provenance/rdtLite#1]
> prov.init("HF-data.R", prov.dir="prov", snapshot.size = 1)
Error in !overwrite : invalid argument type
> traceback()
3: .ddg.set.path(prov.dir, r.script.path, overwrite)
2: .ddg.init(prov.dir, overwrite, save.debug)
1: prov.init("HF-data.R", prov.dir = "prov", snapshot.size = 1)
>

**Comment by blernermhc** [comment]
The error was in the worksheet rather than the code.  Specifically, prov.init does not have a parameter for the script name since this call is written inside a script.
