### ISSUE TITLE
Error with prov.init() and source()

### ISSUE THREAD

**Issue by RoseSheehan** [End-to-end-provenance/rdtLite#3]
In at least one case, rdtLite gives an error when source() is used after prov.init() is called. The error message is:
`Error in showConnections(TRUE)[as.character(sourced.file.name), "description"] :
  subscript out of bounds`

showConnections() is called in this file: https://github.com/End-to-end-provenance/rdtLite/blob/master/R/DataNodes.R in the function .ddg.get.node.val. 

An example that causes this error:
```
rdtLite::prov.init(prov.dir = "provenance")  # begin provenance execution

# run the scripts
source("gap-fill-shaler.R")
source("combine-shaler-fisher.R")

rdtLite::prov.quit()
```

The sourced scripts in this example are from https://harvardforest1.fas.harvard.edu/exist/apps/datasets/showData.html?id=HF300, but it may occur on other scripts as well.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/rdtLite/commit/db8d86c4d5cb9befbf7e5fc995303839b62b3939
